language: csharp
solution: SkiRent.sln
deploy:
  provider: heroku
  api_key:
    secure: tCiycnXFXpOY7eQVyoRsvXispE9pHfrLlp2qO00wMV09NlUwR2W31Q9aj4ZJVnCJ2GaQqs79Ut+xTXGPfBcNfqlSuw6VRGMesVuqKraoo98ysaoxO5EttU0rm6wsl3FveXl9j9xAReD3bo59d5bBlMYd0HG3g2zq4/Jq+7en00IIaH/UzTdJwZm+ue41y+g6BT3PHrGSGA1ZxAY2d8NJvT9Y6/TtZNpl2Vce4uB2Pst8R1/huSm4Oew5dep02DxiQLk4xREhPekdA0zrmoR+sOIUuQYbr15Mz13jbgkYTv5mJhY4fq5/xZZ4sEovwScoQd7CHKbaY4N9f8BKsiU1vq6cOBVDblicaMW5sFV/3SWqhviIwFCOUqiHeVqe3ofyjDDVTEFOwyiXFFeBLf4SLTBMNRy0EzaPmgDrxsCJLd3Tay6R0XmQqy2pwApQsjgmhC65X6EGCtnP3iptgEUt2lwkopz49zdqN1h+cmTFEVS/3cbMwB3blGsGfwPURi5a3U79GBrXBVneswbG/4r00scc/w2JYFZULYyGGuMkELmAkI5wQyEJQsNtUUWSQW0loKCeGYr/9HViHsDlvWDLAanZQwu+ekSFElRtLbq6jEvcPe7UZ1rs9A+P2lbeakJStCiXnJk7l0ejNWMDLVdO1IYv+zOl7HpywXkq7n/7nSc=
